notifications:
  email: false
language: ruby
rvm:
  - 2.3.3
services:
  - postgresql
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - CC_TEST_REPORTER_ID=9e086a3d80910b05d16fa32889989d7cb058ca81153531de35ebf66d17344b9a

before_install:
  - gem update --system
  - gem --version

cache: bundler
bundler_args: --without production development
before_script:
  - nvm install stable && nvm alias default stable
  - npm install npm@latest -g
  - npm install -g yarn
  - npm --version
  - yarn install
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
