language: ruby
rvm:
  - 2.3.3
services:
  - postgresql
env:
- SECRET_KEY_BASRE=AUFXrZCOun8ZmxNfZeyhUVGNW0yTejYvretzA7ezkqZiK4aMIAgX5zbI4csePmkNbHQJi2rwRZWfLTfy6EbxsUU4bIeUuuJGk7T59cKA561NJ1nueGweH3JPgIl37PlfVXxQ1Jc1k8Pk5WSqfr3IeSldbA68nvzsATL2kJBA10els486SX5LoeWLkqUvsDqRz3btlNle SECRET_TOKEN=Mxz1p7kXV9sleqsCFQtSgjTvkdbERwwZ8pBG7Jjk6DLkGXUHed
env:
- NOKOGIRI_USE_SYSTEM_LIBRARIES=true

cache: bundler
bundler_args: --without production development
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml

addons:
  code_climate:
    repo_token: 9e086a3d80910b05d16fa32889989d7cb058ca81153531de35ebf66d17344b9a

