version: '2'

services:
  postgres:
    image: 'postgres:9.6'
    environment:
      POSTGRES_USER: 'glassy-collections'
      POSTGRES_PASSWORD: 'yourpassword'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  webapp:
    depends_on:
      - 'postgres'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/src/glassy-collections'
    env_file:
      - '.env'

volumes:
  postgres:
