version: 2
jobs:
  test-job:
    working_directory: ~/glassy-collections
    parallelism: 1
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
          RAILS_ENV: test
      - image: circleci/postgres:9.4.12-alpine

    steps:
      - checkout

      - run: date +%U-%Y > 'date-cache-key.txt'

      ## Bundler
      # Restore Cache
      - restore_cache:
          keys:
            - gem-cache-{{ checksum "Gemfile.lock" }}
            - gem-cache-date-{{ checksum "date-cache-key.txt" }}
      # Install
      - run: bundle check --path vendor/bundle || bundle install --path vendor/bundle
      # Store Cache
      - save_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - save_cache:
          key: gem-cache-date-{{ checksum "date-cache-key.txt" }}
          paths:
            - vendor/bundle

      - type: shell
        command: |
          bundle exec rubocop \
            --config .rubocop.yml \
            -r $(bundle show rubocop-junit-formatter)/lib/rubocop/formatter/junit_formatter.rb \
            --format RuboCop::Formatter::JUnitFormatter \
            --out /tmp/test-results/rubocop.xml \
            --format progress \
            --force-exclusion \
            $(bundle exec rubocop --list-target-files | circleci tests split --split-by=filesize)

      ## Yarn
      # Restore Cache
      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
      # Install
      - run: yarn install --cache-folder vendor/yarn
      # Store Cache
      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - vendor/yarn
            - node_modules

      - restore_cache:
          keys:
            - asset-cache-{{ .Branch }}
            - asset-cache
      - run: bundle exec rake assets:precompile
      - save_cache:
          key: asset-cache-{{ .Branch }}-{{ epoch }}
          paths:
            - public/assets
            - tmp/cache/assets/sprockets
            - tmp/cache/webpacker
            - public/packs-test

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Database setup
      - run: bundle exec rake db:create db:schema:load --trace

      # Run rspec in parallel
      - type: shell
        command: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      # Save artifacts
      - type: store_test_results
        path: /tmp/test-results
      - store_artifacts:
          path: ./tmp/screenshots
  deploy:
    docker:
      - image: circleci/ruby:2.5.1
    steps:
      - add_ssh_keys:
          fingerprints:
            - "27:70:c5:09:00:c4:03:97:13:2e:f5:47:e4:a2:3f:97"
      - checkout
      - run: |
          echo 'dokku.coreyja.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBG2yW0ZfNQWo1fXW1Tca2rTJE9dcN+8uCadvIp0YSsrgFd/6qv14KCR+ClmmIpBqXQV04yjZ3b09P6APJrQm3wg=' >> ~/.ssh/known_hosts
      - run:
          name: Deploy with git push
          command: |
            git push $GIT_DEPLOY_USERNAME@$GIT_DEPLOY_HOST:glassy-collections master
workflows:
  version: 2
  test-deploy:
    jobs:
      - test-job
      - deploy:
          requires:
            - test-job
          filters:
            branches:
              only: master
